"""
ood_aware_heads.py

Tests whether specific attention heads in Pythia-1.4b carry an internal
OOD signal — different entropy patterns when processing real vs synthetic text —
and whether that signal survives recursive collapse.

Hypothesis (from your other project): LLMs have a "script-level OOD detector"
implemented in a sparse subset of attention heads, which responds to out-of-
distribution input but whose signal is ignored by the rest of the model.

In the context of recursive self-distillation:
  - Real text = TinyStories validation (Gen0 training distribution)
  - Synthetic text = text generated by Pythia Gen5 (collapsed distribution)
  - If heads respond differently to these two inputs → internal OOD signal exists
  - If that differential WEAKENS across generations → the model goes progressively
    blind to its own synthetic distribution as it collapses
  - If the differential PERSISTS in Gen5 despite +1426% PPL → the model "knows"
    but can't act on it — your "ignored OOD detector" confirmed

Three measurements per head per generation:
  1. entropy_diff: mean attention entropy on synthetic - mean entropy on real
     (positive = head spreads more on synthetic; negative = more focused)
  2. entropy_disc: AUROC of per-head entropy for real vs synthetic classification
     (>0.5 means head discriminates; close to 1.0 = strong OOD-aware head)
  3. entropy_delta_gen: how the discrimination ability changes Gen0→Gen5
     (weakening signal → model losing OOD awareness with collapse)

Cross with FIM:
  - Are OOD-aware heads (high AUROC) in high-FIM or low-FIM blocks?
  - Does FIM predict which heads lose their OOD signal fastest?
  - Connection to paper: high-FIM blocks drift most in Pythia → those heads
    may lose OOD awareness earliest

Uses TransformerLens hook_pattern (attention weights) directly.
No SAE, no training. Pure forward pass analysis.

Run: python scripts/ood_aware_heads.py
Out: results/circuit_analysis/ood_aware_heads.json
     results/circuit_analysis/ood_aware_heads.png
"""

import json
import os
import numpy as np
import torch
from scipy import stats
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from datasets import load_dataset
from transformers import GPTNeoXForCausalLM, AutoTokenizer

ROOT    = r"D:\Thaman\Work\hessian-spectral-analysis"
OUT_DIR = os.path.join(ROOT, "results", "circuit_analysis")
CACHE   = os.path.join(OUT_DIR, "ood_aware_heads.json")
PLOT    = os.path.join(OUT_DIR, "ood_aware_heads.png")

FIM_FILE = os.path.join(ROOT, "results", "pythia-1.4b_treatment_gen_0", "perblock_fim.json")

PYTHIA_BASE = "EleutherAI/pythia-1.4b"
PYTHIA_GENS = {
    gen: os.path.join(ROOT, "models", f"pythia-1.4b_treatment_gen_{gen}")
    for gen in range(1, 6)
}
# Use gen5 synthetic data if it exists from the treatment run
SYNTH_PATHS = [
    os.path.join(ROOT, "data", f"pythia-1.4b_treatment_synthetic_gen_5"),  # HF dataset
    os.path.join(ROOT, "results", "fim_block_freeze", "synthetic_gen_5.txt"),  # text file
]

N_PROMPTS = 200   # real prompts
N_SYNTH   = 200   # synthetic prompts

os.makedirs(OUT_DIR, exist_ok=True)


# ── FIM ───────────────────────────────────────────────────────────────────────

def load_fim(fim_file):
    with open(fim_file) as f:
        d = json.load(f)
    fim_attn = {b["block_idx"]: b["attention"]["top"] for b in d["blocks"]}
    fim_mlp  = {b["block_idx"]: b["mlp"]["top"]       for b in d["blocks"]}
    return fim_attn, fim_mlp


# ── data ──────────────────────────────────────────────────────────────────────

def load_real_prompts(n):
    ds = load_dataset("roneneldan/TinyStories", split="validation", streaming=True)
    prompts = []
    for item in ds:
        prompts.append(item["text"][:256])
        if len(prompts) >= n:
            break
    return prompts


def load_synthetic_prompts(n):
    """Load synthetic text from gen5 if available, otherwise generate on the fly."""
    # Try HF dataset first
    for path in SYNTH_PATHS:
        if os.path.exists(path):
            if path.endswith(".txt"):
                with open(path, encoding="utf-8") as f:
                    texts = f.read().split("\n---\n")
                texts = [t.strip() for t in texts if t.strip()]
                print(f"  Loaded {len(texts)} synthetic samples from {path}")
                return texts[:n]
            else:
                # HF dataset on disk
                try:
                    from datasets import load_from_disk
                    ds = load_from_disk(path)
                    texts = [ds[i]["text"][:256] for i in range(min(n, len(ds)))]
                    print(f"  Loaded {len(texts)} synthetic samples from {path}")
                    return texts
                except Exception:
                    pass

    # Fall back: use the treatment gen5 txt files in results/
    gen5_txt = os.path.join(ROOT, "results", "pythia-1.4b_treatment_gen_5.txt")
    if os.path.exists(gen5_txt):
        with open(gen5_txt, encoding="utf-8") as f:
            lines = [l.strip() for l in f if l.strip()]
        print(f"  Loaded {len(lines[:n])} synthetic lines from {gen5_txt}")
        return lines[:n]

    print("  WARNING: No synthetic data found. Generating from Pythia Gen5...")
    return None   # handled in main


def generate_synthetic_prompts(model, tokenizer, n, device):
    """Generate synthetic text from Gen5 Pythia if no cached data exists."""
    ds = load_dataset("roneneldan/TinyStories", split="train", streaming=True)
    seed_prompts = []
    for item in ds:
        seed_prompts.append(item["text"][:32])
        if len(seed_prompts) >= n:
            break

    model.eval()
    generated = []
    bs = 16
    tokenizer.padding_side = "left"
    with torch.no_grad():
        for i in range(0, len(seed_prompts), bs):
            batch = seed_prompts[i:i+bs]
            enc = tokenizer(batch, return_tensors="pt", truncation=True,
                            max_length=32, padding=True).to(device)
            out = model.generate(**enc, max_new_tokens=192, do_sample=True,
                                  temperature=0.7, top_p=0.95,
                                  pad_token_id=tokenizer.eos_token_id)
            for seq in out:
                generated.append(tokenizer.decode(seq, skip_special_tokens=True)[:256])
    tokenizer.padding_side = "right"
    return generated[:n]


# ── attention entropy ─────────────────────────────────────────────────────────

def renyi_entropy_2(attn_weights):
    """
    2-Rényi entropy of attention distribution per head.
    H_2(p) = -log(sum(p^2))  — used in Head Entropy paper (arxiv 2602.13699).
    More sensitive to peaked distributions than Shannon entropy.
    attn_weights: (n_heads, seq_len, seq_len) or (seq_len, seq_len) per head
    Returns: (n_heads,) entropy values
    """
    # p: (n_heads, seq_len) — attended-from distribution at last position
    # Use mean over sequence positions for stability
    p = attn_weights.mean(dim=-2)   # (n_heads, seq_len)
    p = p / (p.sum(dim=-1, keepdim=True) + 1e-10)
    sum_p2 = (p ** 2).sum(dim=-1)   # (n_heads,)
    entropy = -torch.log(sum_p2 + 1e-10)
    return entropy.cpu().float()


def collect_head_entropies(model_path, tokenizer, prompts, device,
                            n_layers, n_heads, is_base=False):
    """
    For each prompt, run Pythia and collect per-head 2-Rényi entropy at each layer.
    Returns: (n_prompts, n_layers, n_heads) array
    """
    from transformers import GPTNeoXForCausalLM

    if is_base:
        model = GPTNeoXForCausalLM.from_pretrained(
            PYTHIA_BASE, torch_dtype=torch.bfloat16,
            attn_implementation="eager").to(device)
    else:
        model = GPTNeoXForCausalLM.from_pretrained(
            model_path, torch_dtype=torch.bfloat16,
            attn_implementation="eager").to(device)
    model.eval()

    all_entropies = []   # (n_prompts, n_layers, n_heads)

    with torch.no_grad():
        for prompt in prompts:
            enc = tokenizer(prompt, return_tensors="pt", truncation=True,
                            max_length=128).to(device)
            if enc["input_ids"].shape[1] < 4:
                continue

            out = model(**enc, output_attentions=True)
            # out.attentions: tuple of (1, n_heads, seq_len, seq_len) per layer
            layer_entropies = []
            for layer_attn in out.attentions:
                # layer_attn: (1, n_heads, seq_len, seq_len)
                attn = layer_attn[0]   # (n_heads, seq_len, seq_len)
                ent = renyi_entropy_2(attn)   # (n_heads,)
                layer_entropies.append(ent.numpy())
            all_entropies.append(np.array(layer_entropies))  # (n_layers, n_heads)

    del model
    if torch.cuda.is_available(): torch.cuda.empty_cache()

    return np.array(all_entropies)   # (n_prompts, n_layers, n_heads)


# ── discrimination metric ─────────────────────────────────────────────────────

def head_discrimination(entropies_real, entropies_synth):
    """
    For each head (layer, head_idx), compute:
      - mean entropy on real and synthetic
      - entropy_diff = mean_synth - mean_real
      - AUROC: how well does entropy alone discriminate real vs synthetic?
        (label 0 = real, label 1 = synthetic)
    Returns: (n_layers, n_heads) arrays for diff and auroc
    """
    n_layers = entropies_real.shape[1]
    n_heads  = entropies_real.shape[2]

    diff_mat  = np.zeros((n_layers, n_heads))
    auroc_mat = np.zeros((n_layers, n_heads))

    for l in range(n_layers):
        for h in range(n_heads):
            real_h  = entropies_real[:, l, h]   # (n_real_prompts,)
            synth_h = entropies_synth[:, l, h]  # (n_synth_prompts,)

            diff_mat[l, h] = float(np.mean(synth_h) - np.mean(real_h))

            # AUROC: label 0 = real, 1 = synthetic
            labels = np.array([0] * len(real_h) + [1] * len(synth_h))
            scores = np.concatenate([real_h, synth_h])
            try:
                auroc = roc_auc_score(labels, scores)
                # Ensure AUROC > 0.5 (flip if needed — direction doesn't matter,
                # we care about discrimination ability not direction)
                auroc_mat[l, h] = max(auroc, 1 - auroc)
            except Exception:
                auroc_mat[l, h] = 0.5

    return diff_mat, auroc_mat


def sig(p):
    if p is None: return ""
    return "**" if p < 0.01 else ("*" if p < 0.05 else "")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    if os.path.exists(CACHE):
        print(f"Cache hit: {CACHE}")
        with open(CACHE) as f:
            results = json.load(f)
        plot(results)
        print_summary(results)
        return

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    fim_attn, fim_mlp = load_fim(FIM_FILE)
    n_layers = 24   # Pythia-1.4b
    n_heads  = 16

    # Load prompts
    print("Loading real prompts...")
    real_prompts = load_real_prompts(N_PROMPTS)
    print(f"  {len(real_prompts)} real prompts")

    print("Loading synthetic prompts...")
    synth_prompts = load_synthetic_prompts(N_SYNTH)

    tokenizer = AutoTokenizer.from_pretrained(PYTHIA_BASE)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # If no cached synthetic data, generate from Gen5
    if synth_prompts is None:
        print("  Generating from Pythia Gen5...")
        gen5_path = PYTHIA_GENS.get(5)
        if gen5_path and os.path.exists(gen5_path):
            gen5_model = GPTNeoXForCausalLM.from_pretrained(
                gen5_path, torch_dtype=torch.bfloat16,
                attn_implementation="eager").to(device)
            synth_prompts = generate_synthetic_prompts(
                gen5_model, tokenizer, N_SYNTH, device)
            del gen5_model
            torch.cuda.empty_cache()
        else:
            print("ERROR: No Gen5 model found. Run treatment protocol first.")
            return
    print(f"  {len(synth_prompts)} synthetic prompts")

    gen_results = {}

    # ── Gen0 baseline ──────────────────────────────────────────────────────────
    print(f"\nGen0 (base model)...")
    ent_real_g0  = collect_head_entropies(None, tokenizer, real_prompts,
                                           device, n_layers, n_heads, is_base=True)
    ent_synth_g0 = collect_head_entropies(None, tokenizer, synth_prompts,
                                           device, n_layers, n_heads, is_base=True)
    diff_g0, auroc_g0 = head_discrimination(ent_real_g0, ent_synth_g0)

    n_ood_g0 = int((auroc_g0 > 0.65).sum())
    top_heads_g0 = np.unravel_index(np.argsort(auroc_g0.ravel())[-10:], auroc_g0.shape)
    print(f"  Heads with AUROC>0.65 (OOD-aware): {n_ood_g0} / {n_layers*n_heads}")
    print(f"  Top-10 discriminating heads: "
          f"{list(zip(top_heads_g0[0].tolist(), top_heads_g0[1].tolist()))}")

    gen_results["0"] = {
        "auroc_mean": float(auroc_g0.mean()),
        "auroc_max":  float(auroc_g0.max()),
        "n_ood_aware_065": n_ood_g0,
        "diff_mean":  float(np.abs(diff_g0).mean()),
        "auroc_matrix": auroc_g0.tolist(),
        "diff_matrix":  diff_g0.tolist(),
    }

    # ── Gen1–Gen5 ──────────────────────────────────────────────────────────────
    for gen, model_path in PYTHIA_GENS.items():
        if not os.path.exists(model_path):
            print(f"  Gen{gen} not found, skipping.")
            continue

        print(f"\nGen{gen}...")
        ent_real  = collect_head_entropies(model_path, tokenizer, real_prompts,
                                            device, n_layers, n_heads)
        ent_synth = collect_head_entropies(model_path, tokenizer, synth_prompts,
                                            device, n_layers, n_heads)
        diff, auroc = head_discrimination(ent_real, ent_synth)

        n_ood = int((auroc > 0.65).sum())
        print(f"  OOD-aware heads (AUROC>0.65): {n_ood} / {n_layers*n_heads}")
        print(f"  Mean AUROC: {auroc.mean():.4f}  Max: {auroc.max():.4f}")

        # FIM correlation: does FIM_attn predict which heads are OOD-aware?
        # Aggregate AUROC per block (mean across heads in that block)
        block_auroc   = [float(auroc[l].mean()) for l in range(n_layers)]
        block_log_fim = [np.log10(fim_attn.get(l, np.nan)) if fim_attn.get(l, 0) > 0
                         else np.nan for l in range(n_layers)]
        valid = [(f, a) for f, a in zip(block_log_fim, block_auroc) if np.isfinite(f)]
        if len(valid) >= 4:
            xs, ys = zip(*valid)
            rho, p = stats.spearmanr(xs, ys)
            print(f"  ρ(FIM_attn, block_AUROC) = {rho:+.3f}{sig(p)}  p={p:.4f}")
        else:
            rho, p = None, None

        # AUROC degradation vs Gen0: do OOD-aware heads lose their signal?
        auroc_delta = auroc - auroc_g0   # (n_layers, n_heads) — negative = degraded
        degraded_heads = int((auroc_delta < -0.05).sum())
        improved_heads = int((auroc_delta >  0.05).sum())
        print(f"  Heads that LOST OOD signal vs Gen0 (ΔAUROC<-0.05): {degraded_heads}")
        print(f"  Heads that GAINED OOD signal vs Gen0 (ΔAUROC>+0.05): {improved_heads}")

        gen_results[str(gen)] = {
            "auroc_mean":       float(auroc.mean()),
            "auroc_max":        float(auroc.max()),
            "n_ood_aware_065":  n_ood,
            "diff_mean":        float(np.abs(diff).mean()),
            "auroc_matrix":     auroc.tolist(),
            "diff_matrix":      diff.tolist(),
            "auroc_delta_vs_g0": auroc_delta.tolist(),
            "degraded_heads":   degraded_heads,
            "improved_heads":   improved_heads,
            "fim_rho":          rho,
            "fim_p":            p,
        }

    output = {
        "model": "Pythia-1.4b",
        "n_layers": n_layers, "n_heads": n_heads,
        "n_real": len(real_prompts), "n_synth": len(synth_prompts),
        "fim_attn": {str(k): v for k, v in fim_attn.items()},
        "generations": gen_results,
    }

    with open(CACHE, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nCached: {CACHE}")

    plot(output)
    print_summary(output)


# ── plot ──────────────────────────────────────────────────────────────────────

def plot(results):
    gens     = sorted(results["generations"].keys(), key=int)
    gen_nums = [int(g) for g in gens]
    n_layers = results["n_layers"]
    n_heads  = results["n_heads"]

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    # ── Top-left: mean AUROC trajectory ──────────────────────────────────────
    ax = axes[0][0]
    mean_aurocs = [results["generations"][g]["auroc_mean"] for g in gens]
    max_aurocs  = [results["generations"][g]["auroc_max"]  for g in gens]
    n_ood       = [results["generations"][g]["n_ood_aware_065"] for g in gens]
    ax.plot(gen_nums, mean_aurocs, "o-b", label="Mean AUROC")
    ax.plot(gen_nums, max_aurocs,  "s-r", label="Max AUROC")
    ax.axhline(0.5, color="k", lw=0.8, ls="--", label="Chance")
    ax.axhline(0.65, color="g", lw=0.8, ls=":", label="OOD-aware threshold")
    ax.set_xlabel("Generation"); ax.set_ylabel("AUROC (real vs synthetic)")
    ax.set_title("OOD discrimination ability across generations\n"
                 "If DECREASING: model loses internal OOD signal as it collapses")
    ax.legend(fontsize=8); ax.grid(True, alpha=0.3); ax.set_xticks(gen_nums)

    # ── Top-middle: n_ood_aware_heads trajectory ──────────────────────────────
    ax = axes[0][1]
    ax.plot(gen_nums, n_ood, "o-m")
    ax.set_xlabel("Generation"); ax.set_ylabel("Number of OOD-aware heads (AUROC>0.65)")
    ax.set_title("Count of OOD-aware heads across generations\n"
                 "Declining count = model going blind to own synthetic distribution")
    ax.grid(True, alpha=0.3); ax.set_xticks(gen_nums)

    # ── Top-right: FIM correlation trajectory ────────────────────────────────
    ax = axes[0][2]
    fim_rhos = [results["generations"][g].get("fim_rho") for g in gens if int(g) > 0]
    fim_ps   = [results["generations"][g].get("fim_p")   for g in gens if int(g) > 0]
    non_zero_gens = [int(g) for g in gens if int(g) > 0]
    valid = [(g, r, p) for g, r, p in zip(non_zero_gens, fim_rhos, fim_ps)
             if r is not None]
    if valid:
        gs, rs, ps = zip(*valid)
        colors = ["green" if p and p < 0.05 else "gray" for p in ps]
        ax.scatter(gs, rs, c=colors, s=80, zorder=3)
        ax.plot(gs, rs, "-", color="gray", alpha=0.5)
    ax.axhline(0, color="k", lw=0.8, ls="--")
    ax.set_xlabel("Generation"); ax.set_ylabel("Spearman ρ(FIM_attn, block_AUROC)")
    ax.set_title("Do high-FIM blocks have stronger OOD heads?\n"
                 "Green = significant; want: consistent sign across gens")
    ax.grid(True, alpha=0.3); ax.set_xticks(non_zero_gens if valid else [])

    # ── Bottom-left: AUROC heatmap at Gen0 ───────────────────────────────────
    ax = axes[1][0]
    g0_auroc = np.array(results["generations"]["0"]["auroc_matrix"])
    im = ax.imshow(g0_auroc, aspect="auto", cmap="hot",
                   vmin=0.5, vmax=1.0, origin="lower")
    plt.colorbar(im, ax=ax, label="AUROC")
    ax.set_xlabel("Head index"); ax.set_ylabel("Layer")
    ax.set_title("Gen0 AUROC per head (real vs synthetic)\nHot = strong OOD discrimination")

    # ── Bottom-middle: AUROC change Gen0→Gen5 ────────────────────────────────
    ax = axes[1][1]
    last_gen = str(max(int(g) for g in gens))
    if "auroc_delta_vs_g0" in results["generations"][last_gen]:
        delta = np.array(results["generations"][last_gen]["auroc_delta_vs_g0"])
        im2 = ax.imshow(delta, aspect="auto", cmap="RdBu_r",
                        vmin=-0.3, vmax=0.3, origin="lower")
        plt.colorbar(im2, ax=ax, label="ΔAUROC (Gen5 - Gen0)")
        ax.set_xlabel("Head index"); ax.set_ylabel("Layer")
        ax.set_title(f"AUROC change Gen0→Gen{last_gen}\n"
                     "Red = lost OOD signal, Blue = gained OOD signal")

    # ── Bottom-right: block-level AUROC vs FIM ────────────────────────────────
    ax = axes[1][2]
    fim_attn = {int(k): v for k, v in results["fim_attn"].items()}
    last_auroc = np.array(results["generations"][last_gen]["auroc_matrix"])
    block_auroc_vals = [float(last_auroc[l].mean()) for l in range(n_layers)]
    log_fim_vals = [np.log10(fim_attn.get(l, np.nan)) if fim_attn.get(l, 0) > 0
                    else np.nan for l in range(n_layers)]
    valid = [(f, a, l) for l, (f, a) in enumerate(zip(log_fim_vals, block_auroc_vals))
             if np.isfinite(f)]
    if valid:
        xs, ys, ls = zip(*valid)
        ax.scatter(xs, ys, s=60, c=ls, cmap="viridis")
        for x, y, layer in zip(xs, ys, ls):
            ax.annotate(f"L{layer}", (x, y), textcoords="offset points",
                        xytext=(3, 3), fontsize=7)
    fim_rho = results["generations"][last_gen].get("fim_rho")
    fim_p   = results["generations"][last_gen].get("fim_p")
    rho_str = f"ρ={fim_rho:+.3f}{sig(fim_p)}" if fim_rho else "ρ=N/A"
    ax.set_xlabel("log10(FIM_attn)"); ax.set_ylabel(f"Mean block AUROC (Gen{last_gen})")
    ax.set_title(f"FIM vs OOD-awareness at Gen{last_gen}\n{rho_str}\n"
                 "Color = layer depth")
    ax.grid(True, alpha=0.3)

    plt.suptitle(
        "OOD-Aware Attention Heads in Pythia-1.4b: Real vs Synthetic Text\n"
        "Hypothesis: heads encode internal OOD signal that is ignored during generation.",
        fontsize=11, fontweight="bold")
    plt.tight_layout()
    plt.savefig(PLOT, dpi=150, bbox_inches="tight")
    print(f"Plot: {PLOT}")


def print_summary(results):
    gens = sorted(results["generations"].keys(), key=int)
    print("\n" + "="*70)
    print("OOD-AWARE HEADS SUMMARY — Pythia-1.4b")
    print("="*70)
    print(f"  {'Gen':>4}  {'mean_AUROC':>11} {'max_AUROC':>10} "
          f"{'n_OOD(>0.65)':>13} {'degraded':>10} {'FIM_rho':>9}")
    print("  " + "─"*65)
    for g in gens:
        r = results["generations"][g]
        fim_rho = r.get("fim_rho")
        fim_p   = r.get("fim_p")
        rho_str = f"{fim_rho:+.3f}{sig(fim_p)}" if fim_rho else "—"
        deg = r.get("degraded_heads", "—")
        print(f"  {int(g):>4}  {r['auroc_mean']:>11.4f} {r['auroc_max']:>10.4f} "
              f"{r['n_ood_aware_065']:>13}  {str(deg):>9}  {rho_str:>9}")
    print()
    print("INTERPRETATION:")
    print("  Declining mean_AUROC: model loses internal OOD signal with collapse")
    print("  Declining n_OOD: fewer heads discriminate real vs synthetic over gens")
    print("  FIM_rho positive: high-FIM blocks have stronger OOD-aware heads")
    print("    → those blocks drift most (parallel) → they also lose OOD signal first")
    print("  FIM_rho negative: low-FIM blocks are the OOD detectors")
    print()
    print("  The 'ignored OOD detector' hypothesis is confirmed if:")
    print("    (a) Gen0 has heads with AUROC >> 0.5 on real vs synthetic")
    print("    (b) those heads persist into later gens despite PPL degrading")
    print("    OR")
    print("    (a) Gen0 has OOD-aware heads")
    print("    (b) those heads progressively lose discrimination as collapse deepens")
    print("        → model becomes blind to its own synthetic distribution")


if __name__ == "__main__":
    main()